nohup python -u train.py \
--data_path ../dataset/MSCOCO/image_sg \
--data_name NM_vgg_mscoco_split2014 \
--vocab_path ./vocab/ \
--num_epochs 20 \
--batch_size 200 \
--gcn_num_layers 1 \
--activation tanh \
--learning_rate 0.0005 \
--lr_update 10 \
--workers 4 \
--logger_name ./runs/NM_vgg_mscoco_BUA_sg_with_sg_label_fusion_with_spice_sg_lstm \
--model_name ./runs/NM_vgg_mscoco_BUA_sg_with_sg_label_fusion_with_spice_sg_lstm \
--max_violation \
--img_dim 2048 \
--no_imgnorm \
--cross_attn t2i \
--bi_gru \
--grad_clip 2 \
--predicate_score_rate 1.0 \
--sg_file_name _image_sg_by_NeuralMotifsVGG_36_25_2.json \
--feature_name NM_BUA \
--caption_data_file_name _caps_with_rel.json \
--alpha 1.0 \
--fusion_activation tanh \
--fusion_method concatenate \
--val_step 2000 > NM_vgg_mscoco_BUA_sg_with_sg_label_fusion_with_spice_sg_lstm.log 2>&1 &